FROM node:20.12.2 AS base
ENV MODE production
ENV NUXT_HOST 0.0.0.0
ENV NUXT_PORT 5000

ARG TONCONNECT_MANIFEST_URL
ENV TONCONNECT_MANIFEST_URL=${TONCONNECT_MANIFEST_URL}

ARG TELEGRAM_MINI_APP_BOT_URL
ENV TELEGRAM_MINI_APP_BOT_URL=${TELEGRAM_MINI_APP_BOT_URL}

ARG TONCENTER_URL
ENV TONCENTER_URL=${TONCENTER_URL}

ARG ETHERS_PROVIDER_URL
ENV ETHERS_PROVIDER_URL=${ETHERS_PROVIDER_URL}

ARG ETHERS_CONTRACT_ADDRESS
ENV ETHERS_CONTRACT_ADDRESS=${ETHERS_CONTRACT_ADDRESS}

ARG SWAP_PAYLOAD_TO_ADDRESS
ENV SWAP_PAYLOAD_TO_ADDRESS=${SWAP_PAYLOAD_TO_ADDRESS}

ARG SWAP_PAYLOAD_JSON_TARGET
ENV SWAP_PAYLOAD_JSON_TARGET=${SWAP_PAYLOAD_JSON_TARGET}

ARG SWAP_PAYLOAD_JSON_MINT_TOKEN_ADDRESS
ENV SWAP_PAYLOAD_JSON_MINT_TOKEN_ADDRESS=${SWAP_PAYLOAD_JSON_MINT_TOKEN_ADDRESS}

# Create app directory
WORKDIR /usr/src/app
# Copy package.json for installing dependencies
COPY package.json .
COPY package-lock.json .
# Install app dependencies
RUN npm i
# Copy app source with common folder
COPY . /usr/src/app
# Build app
RUN npm run build
# Start server
CMD [ "node", ".output/server/index.mjs" ]
